"""workchat: conversations messages agent_actions

Revision ID: 23b3888b116f
Revises: c3a7f1b9d2e4
Create Date: 2026-06-14 23:27:12.817073

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23b3888b116f"
down_revision: str | None = "c3a7f1b9d2e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_conversations_project_id_projects"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(op.f("ix_conversations_tenant_id"), "conversations", ["tenant_id"], unique=False)
    op.create_index("ix_conversations_tenant_project", "conversations", ["tenant_id", "project_id"], unique=False)
    op.create_table(
        "agent_actions",
        sa.Column("conversation_id", sa.String(length=32), nullable=True),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_by_user_id", sa.String(length=32), nullable=False),
        sa.Column("agent_id", sa.String(length=32), nullable=False),
        sa.Column("approved_by_user_id", sa.String(length=32), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column("permissions_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("skill_invocation_id", sa.String(length=32), nullable=True),
        sa.Column("result_ref_type", sa.String(length=32), nullable=True),
        sa.Column("result_ref_id", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("updated_by", sa.String(length=32), nullable=True),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["agent_id"], ["ai_agents.id"], name=op.f("fk_agent_actions_agent_id_ai_agents")),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"], ["users.id"], name=op.f("fk_agent_actions_approved_by_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_agent_actions_conversation_id_conversations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_agent_actions_project_id_projects")),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"], ["users.id"], name=op.f("fk_agent_actions_requested_by_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_actions")),
    )
    op.create_index("ix_agent_actions_project_status", "agent_actions", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_agent_actions_status"), "agent_actions", ["status"], unique=False)
    op.create_index(op.f("ix_agent_actions_tenant_id"), "agent_actions", ["tenant_id"], unique=False)
    op.create_index(
        "ix_agent_actions_tenant_status_created", "agent_actions", ["tenant_id", "status", "created_at"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("agent_action_id", sa.String(length=32), nullable=True),
        sa.Column("work_item_id", sa.String(length=32), nullable=True),
        sa.Column("knowledge_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_action_id"], ["agent_actions.id"], name=op.f("fk_messages_agent_action_id_agent_actions")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["work_item_id"], ["work_items.id"], name=op.f("fk_messages_work_item_id_work_items")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index("ix_messages_conversation_created", "messages", ["conversation_id", "created_at"], unique=False)
    op.create_index(op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_agent_actions_tenant_status_created", table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_tenant_id"), table_name="agent_actions")
    op.drop_index(op.f("ix_agent_actions_status"), table_name="agent_actions")
    op.drop_index("ix_agent_actions_project_status", table_name="agent_actions")
    op.drop_table("agent_actions")
    op.drop_index("ix_conversations_tenant_project", table_name="conversations")
    op.drop_index(op.f("ix_conversations_tenant_id"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
