"""work_items tables and project sequence

Revision ID: 35d6bb78933b
Revises: 081cc197c12d
Create Date: 2026-06-13 17:44:57.220552

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35d6bb78933b"
down_revision: str | None = "081cc197c12d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_items",
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("assignee_id", sa.String(length=32), nullable=True),
        sa.Column("reporter_id", sa.String(length=32), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("source_ref_id", sa.String(length=64), nullable=True),
        sa.Column("ai_summary", sa.Text(), nullable=True),
        sa.Column("acceptance_criteria", sa.Text(), nullable=True),
        sa.Column("custom_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("updated_by", sa.String(length=32), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], name=op.f("fk_work_items_assignee_id_users")),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_work_items_project_id_projects"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], name=op.f("fk_work_items_reporter_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_items")),
        sa.UniqueConstraint("project_id", "key", name="uq_work_items_project_key"),
        sa.UniqueConstraint("project_id", "seq", name="uq_work_items_project_seq"),
    )
    op.create_index(op.f("ix_work_items_assignee_id"), "work_items", ["assignee_id"], unique=False)
    op.create_index("ix_work_items_project_status", "work_items", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_work_items_tenant_id"), "work_items", ["tenant_id"], unique=False)
    op.create_table(
        "work_item_activities",
        sa.Column("work_item_id", sa.String(length=32), nullable=False),
        sa.Column("actor_type", sa.String(length=20), nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("field", sa.String(length=50), nullable=True),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_work_item_activities_work_item_id_work_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_item_activities")),
    )
    op.create_index(op.f("ix_work_item_activities_tenant_id"), "work_item_activities", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_work_item_activities_work_item_id"), "work_item_activities", ["work_item_id"], unique=False
    )
    op.create_table(
        "work_item_comments",
        sa.Column("work_item_id", sa.String(length=32), nullable=False),
        sa.Column("author_type", sa.String(length=20), nullable=False),
        sa.Column("author_id", sa.String(length=32), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_work_item_comments_work_item_id_work_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_item_comments")),
    )
    op.create_index(op.f("ix_work_item_comments_tenant_id"), "work_item_comments", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_work_item_comments_work_item_id"), "work_item_comments", ["work_item_id"], unique=False)
    op.create_table(
        "work_item_relations",
        sa.Column("source_work_item_id", sa.String(length=32), nullable=False),
        sa.Column("target_work_item_id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.String(length=32), nullable=True),
        sa.Column("tenant_id", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_work_item_id <> target_work_item_id", name=op.f("ck_work_item_relations_no_self_relation")
        ),
        sa.ForeignKeyConstraint(
            ["source_work_item_id"],
            ["work_items.id"],
            name=op.f("fk_work_item_relations_source_work_item_id_work_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_work_item_id"],
            ["work_items.id"],
            name=op.f("fk_work_item_relations_target_work_item_id_work_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_item_relations")),
        sa.UniqueConstraint(
            "source_work_item_id", "target_work_item_id", "type", name="uq_work_item_relations_src_tgt_type"
        ),
    )
    op.create_index(
        op.f("ix_work_item_relations_source_work_item_id"), "work_item_relations", ["source_work_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_work_item_relations_target_work_item_id"), "work_item_relations", ["target_work_item_id"], unique=False
    )
    op.create_index(op.f("ix_work_item_relations_tenant_id"), "work_item_relations", ["tenant_id"], unique=False)
    op.add_column("projects", sa.Column("work_item_seq", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "work_item_seq")
    op.drop_index(op.f("ix_work_item_relations_tenant_id"), table_name="work_item_relations")
    op.drop_index(op.f("ix_work_item_relations_target_work_item_id"), table_name="work_item_relations")
    op.drop_index(op.f("ix_work_item_relations_source_work_item_id"), table_name="work_item_relations")
    op.drop_table("work_item_relations")
    op.drop_index(op.f("ix_work_item_comments_work_item_id"), table_name="work_item_comments")
    op.drop_index(op.f("ix_work_item_comments_tenant_id"), table_name="work_item_comments")
    op.drop_table("work_item_comments")
    op.drop_index(op.f("ix_work_item_activities_work_item_id"), table_name="work_item_activities")
    op.drop_index(op.f("ix_work_item_activities_tenant_id"), table_name="work_item_activities")
    op.drop_table("work_item_activities")
    op.drop_index(op.f("ix_work_items_tenant_id"), table_name="work_items")
    op.drop_index("ix_work_items_project_status", table_name="work_items")
    op.drop_index(op.f("ix_work_items_assignee_id"), table_name="work_items")
    op.drop_table("work_items")
    # ### end Alembic commands ###
