"""intake: intake_requests

Revision ID: f255da65bbd9
Revises: 23b3888b116f
Create Date: 2026-06-15 09:54:28.658944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f255da65bbd9'
down_revision: Union[str, None] = '23b3888b116f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_requests',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitter_id', sa.String(length=32), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_category', sa.String(length=40), nullable=True),
    sa.Column('suggested_type', sa.String(length=20), nullable=True),
    sa.Column('suggested_priority', sa.String(length=10), nullable=True),
    sa.Column('suggested_assignee_id', sa.String(length=32), nullable=True),
    sa.Column('triage_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duplicate_work_item_id', sa.String(length=32), nullable=True),
    sa.Column('converted_work_item_id', sa.String(length=32), nullable=True),
    sa.Column('snooze_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['converted_work_item_id'], ['work_items.id'], name=op.f('fk_intake_requests_converted_work_item_id_work_items')),
    sa.ForeignKeyConstraint(['duplicate_work_item_id'], ['work_items.id'], name=op.f('fk_intake_requests_duplicate_work_item_id_work_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_intake_requests_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], name=op.f('fk_intake_requests_submitter_id_users')),
    sa.ForeignKeyConstraint(['suggested_assignee_id'], ['users.id'], name=op.f('fk_intake_requests_suggested_assignee_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_requests')),
    sa.UniqueConstraint('converted_work_item_id', name='uq_intake_requests_converted_work_item')
    )
    op.create_index(op.f('ix_intake_requests_project_id'), 'intake_requests', ['project_id'], unique=False)
    op.create_index('ix_intake_requests_project_status', 'intake_requests', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_intake_requests_tenant_id'), 'intake_requests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intake_requests_tenant_id'), table_name='intake_requests')
    op.drop_index('ix_intake_requests_project_status', table_name='intake_requests')
    op.drop_index(op.f('ix_intake_requests_project_id'), table_name='intake_requests')
    op.drop_table('intake_requests')
    # ### end Alembic commands ###
