/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type ActivityAction = typeof ActivityAction[keyof typeof ActivityAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityAction = {
  created: 'created',
  title_changed: 'title_changed',
  description_changed: 'description_changed',
  assignee_changed: 'assignee_changed',
  priority_changed: 'priority_changed',
  status_changed: 'status_changed',
  commented: 'commented',
  relation_added: 'relation_added',
  relation_removed: 'relation_removed',
  deleted: 'deleted',
} as const;
