/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityOutActorId } from './activityOutActorId';
import type { ActivityOutActor } from './activityOutActor';
import type { ActivityAction } from './activityAction';
import type { ActivityOutField } from './activityOutField';
import type { ActivityOutBefore } from './activityOutBefore';
import type { ActivityOutAfter } from './activityOutAfter';

export interface ActivityOut {
  id: string;
  workItemId: string;
  actorType: string;
  actorId: ActivityOutActorId;
  actor: ActivityOutActor;
  action: ActivityAction;
  field: ActivityOutField;
  before: ActivityOutBefore;
  after: ActivityOutAfter;
  createdAt: string;
}
