/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { AgentActionOutConversationId } from './agentActionOutConversationId';
import type { AgentActionOutMessageId } from './agentActionOutMessageId';
import type { AgentActionType } from './agentActionType';
import type { AgentActionOutArguments } from './agentActionOutArguments';
import type { RiskLevel } from './riskLevel';
import type { AgentActionStatus } from './agentActionStatus';
import type { AgentActionOutApprovedByUserId } from './agentActionOutApprovedByUserId';
import type { AgentActionOutApprovedAt } from './agentActionOutApprovedAt';
import type { AgentActionOutRejectedAt } from './agentActionOutRejectedAt';
import type { AgentActionOutExecutedAt } from './agentActionOutExecutedAt';
import type { AgentActionOutRejectionReason } from './agentActionOutRejectionReason';
import type { AgentActionOutSkillInvocationId } from './agentActionOutSkillInvocationId';
import type { AgentActionOutResultRefType } from './agentActionOutResultRefType';
import type { AgentActionOutResultRefId } from './agentActionOutResultRefId';
import type { AgentActionOutErrorMessage } from './agentActionOutErrorMessage';
import type { AgentActionOutExpiresAt } from './agentActionOutExpiresAt';

export interface AgentActionOut {
  id: string;
  conversationId: AgentActionOutConversationId;
  messageId: AgentActionOutMessageId;
  projectId: string;
  actionType: AgentActionType;
  arguments: AgentActionOutArguments;
  riskLevel: RiskLevel;
  status: AgentActionStatus;
  requestedByUserId: string;
  agentId: string;
  approvedByUserId: AgentActionOutApprovedByUserId;
  approvedAt: AgentActionOutApprovedAt;
  rejectedAt: AgentActionOutRejectedAt;
  executedAt: AgentActionOutExecutedAt;
  rejectionReason: AgentActionOutRejectionReason;
  skillInvocationId: AgentActionOutSkillInvocationId;
  resultRefType: AgentActionOutResultRefType;
  resultRefId: AgentActionOutResultRefId;
  errorMessage: AgentActionOutErrorMessage;
  expiresAt: AgentActionOutExpiresAt;
  createdAt: string;
  updatedAt: string;
}
