/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

/**
 * v0.1 confirmable write actions: the four work_items low_write tools plus the two
intake low_write tools (M6). Read tools (search / summary / list) execute directly and
never become an AgentAction.
 */
export type AgentActionType = typeof AgentActionType[keyof typeof AgentActionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgentActionType = {
  create_work_item: 'create_work_item',
  update_work_item: 'update_work_item',
  transition_work_item: 'transition_work_item',
  comment_work_item: 'comment_work_item',
  create_intake_request: 'create_intake_request',
  accept_intake_request: 'accept_intake_request',
} as const;
