/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type AgentStatus = typeof AgentStatus[keyof typeof AgentStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgentStatus = {
  active: 'active',
  disabled: 'disabled',
} as const;
