/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type AgentActionStatus = typeof AgentActionStatus[keyof typeof AgentActionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgentActionStatus = {
  pending: 'pending',
  approved: 'approved',
  rejected: 'rejected',
  executed: 'executed',
  failed: 'failed',
  expired: 'expired',
} as const;
