/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { AiConnectionOutApiKeyMasked } from './aiConnectionOutApiKeyMasked';

/**
 * Masked, read-only view of the multirag connection (.env-driven, D7). The API token is
NEVER returned in plaintext — only whether it is configured and a masked tail.
 */
export interface AiConnectionOut {
  aiClient: string;
  aiPlatformBaseUrl: string;
  aiPlatformDefaultAgentId: string;
  aiPlatformTimeoutSeconds: number;
  apiKeyConfigured: boolean;
  apiKeyMasked: AiConnectionOutApiKeyMasked;
  intakeTriageProvider: string;
  dashboardInsightsProvider: string;
}
