/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type AuditAction = typeof AuditAction[keyof typeof AuditAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditAction = {
  setupcomplete: 'setup.complete',
  authlogin: 'auth.login',
  authlogout: 'auth.logout',
  invitecreate: 'invite.create',
  inviterevoke: 'invite.revoke',
  inviteaccept: 'invite.accept',
  role_bindingcreate: 'role_binding.create',
  role_bindingdelete: 'role_binding.delete',
  projectcreate: 'project.create',
  projectupdate: 'project.update',
  projectarchive: 'project.archive',
  projectmemberadd: 'project.member.add',
  projectmemberupdate: 'project.member.update',
  projectmemberremove: 'project.member.remove',
  work_itemcreate: 'work_item.create',
  work_itemupdate: 'work_item.update',
  work_itemdelete: 'work_item.delete',
  work_itemtransition: 'work_item.transition',
  work_itemcomment: 'work_item.comment',
  work_itemrelationadd: 'work_item.relation.add',
  work_itemrelationremove: 'work_item.relation.remove',
  skillinvoke: 'skill.invoke',
  aiproposed_actioncreate: 'ai.proposed_action.create',
  agent_actionapprove: 'agent_action.approve',
  agent_actionreject: 'agent_action.reject',
  agent_actionexecute: 'agent_action.execute',
  intakecreate: 'intake.create',
  intakeupdate: 'intake.update',
  intakeaccept: 'intake.accept',
  intakereject: 'intake.reject',
  intakeduplicate: 'intake.duplicate',
  intakesnooze: 'intake.snooze',
  userprofileupdate: 'user.profile.update',
} as const;
