/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { AuditActorType } from './auditActorType';
import type { AuditActorOutId } from './auditActorOutId';
import type { AuditActorOutDisplayName } from './auditActorOutDisplayName';

export interface AuditActorOut {
  type: AuditActorType;
  id: AuditActorOutId;
  displayName: AuditActorOutDisplayName;
}
