/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { AuditActorOut } from './auditActorOut';
import type { AuditLogOutResourceId } from './auditLogOutResourceId';
import type { AuditLogOutProjectId } from './auditLogOutProjectId';
import type { AuditLogOutProjectName } from './auditLogOutProjectName';
import type { AuditLogOutBefore } from './auditLogOutBefore';
import type { AuditLogOutAfter } from './auditLogOutAfter';
import type { AuditLogOutDetail } from './auditLogOutDetail';
import type { AuditLogOutRequestId } from './auditLogOutRequestId';
import type { AuditLogOutIpAddress } from './auditLogOutIpAddress';

export interface AuditLogOut {
  id: string;
  createdAt: string;
  actor: AuditActorOut;
  action: string;
  resourceType: string;
  resourceId: AuditLogOutResourceId;
  projectId: AuditLogOutProjectId;
  projectName: AuditLogOutProjectName;
  before: AuditLogOutBefore;
  after: AuditLogOutAfter;
  detail: AuditLogOutDetail;
  requestId: AuditLogOutRequestId;
  ipAddress: AuditLogOutIpAddress;
}
