/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type AuditActorType = typeof AuditActorType[keyof typeof AuditActorType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditActorType = {
  user: 'user',
  ai_agent: 'ai_agent',
  system: 'system',
} as const;
