/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { CommentAuthorType } from './commentAuthorType';
import type { CommentOutAuthorId } from './commentOutAuthorId';
import type { CommentOutAuthor } from './commentOutAuthor';

export interface CommentOut {
  id: string;
  workItemId: string;
  authorType: CommentAuthorType;
  authorId: CommentOutAuthorId;
  author: CommentOutAuthor;
  body: string;
  createdAt: string;
}
