/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ConversationOutTitle } from './conversationOutTitle';
import type { ConversationOutCreatedBy } from './conversationOutCreatedBy';

export interface ConversationOut {
  id: string;
  projectId: string;
  title: ConversationOutTitle;
  kind: string;
  createdBy: ConversationOutCreatedBy;
  createdAt: string;
  updatedAt: string;
}
