/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { UserOut } from './userOut';
import type { TenantOut } from './tenantOut';
import type { Role } from './role';
import type { Permission } from './permission';
import type { ProjectAccessOut } from './projectAccessOut';
import type { AIContextOut } from './aIContextOut';

export interface CurrentUserContext {
  user: UserOut;
  tenant: TenantOut;
  roles: Role[];
  permissions: Permission[];
  projects: ProjectAccessOut[];
  ai: AIContextOut;
}
