/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { DashboardSummaryOutStatusCounts } from './dashboardSummaryOutStatusCounts';
import type { DashboardSummaryOutTypeCounts } from './dashboardSummaryOutTypeCounts';
import type { DashboardSummaryOutPriorityCounts } from './dashboardSummaryOutPriorityCounts';
import type { DashboardSummaryOutSourceCounts } from './dashboardSummaryOutSourceCounts';
import type { DashboardSummaryOutIntakeStatusCounts } from './dashboardSummaryOutIntakeStatusCounts';
import type { TrendPoint } from './trendPoint';

export interface DashboardSummaryOut {
  totalCount: number;
  statusCounts: DashboardSummaryOutStatusCounts;
  typeCounts: DashboardSummaryOutTypeCounts;
  priorityCounts: DashboardSummaryOutPriorityCounts;
  sourceCounts: DashboardSummaryOutSourceCounts;
  highPriorityCount: number;
  overdueCount: number;
  aiCreatedCount: number;
  intakeRequestCount: number;
  intakeStatusCounts: DashboardSummaryOutIntakeStatusCounts;
  intakeConvertedCount: number;
  intakeConversionRate: number;
  createdTrend: TrendPoint[];
  completedTrend: TrendPoint[];
}
