/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkItemStatus } from './workItemStatus';
import type { WorkItemType } from './workItemType';
import type { WorkItemPriority } from './workItemPriority';
import type { DashboardOverdueItemOutAssigneeId } from './dashboardOverdueItemOutAssigneeId';
import type { DashboardOverdueItemOutAssignee } from './dashboardOverdueItemOutAssignee';
import type { WorkItemSource } from './workItemSource';

export interface DashboardOverdueItemOut {
  id: string;
  key: string;
  title: string;
  status: WorkItemStatus;
  type: WorkItemType;
  priority: WorkItemPriority;
  assigneeId: DashboardOverdueItemOutAssigneeId;
  assignee: DashboardOverdueItemOutAssignee;
  dueAt: string;
  daysOverdue: number;
  source: WorkItemSource;
  createdAt: string;
}
