/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { InsightOut } from './insightOut';
import type { InsightProvenance } from './insightProvenance';

export interface DashboardInsightsOut {
  insights: InsightOut[];
  provenance: InsightProvenance;
}
