/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkloadItemOut } from './workloadItemOut';

export interface DashboardWorkloadOut {
  items: WorkloadItemOut[];
}
