/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { EnvelopeRelationOutData } from './envelopeRelationOutData';

export interface EnvelopeRelationOut {
  code?: number;
  message?: string;
  data?: EnvelopeRelationOutData;
}
