/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { RelationOut } from './relationOut';

export type EnvelopeListRelationOutData = RelationOut[] | null;
