/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { EnvelopeProjectOutData } from './envelopeProjectOutData';

export interface EnvelopeProjectOut {
  code?: number;
  message?: string;
  data?: EnvelopeProjectOutData;
}
