/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { EnvelopeCommentOutData } from './envelopeCommentOutData';

export interface EnvelopeCommentOut {
  code?: number;
  message?: string;
  data?: EnvelopeCommentOutData;
}
