/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { EnvelopeMessageOutData } from './envelopeMessageOutData';

export interface EnvelopeMessageOut {
  code?: number;
  message?: string;
  data?: EnvelopeMessageOutData;
}
