/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { EnvelopePageMessageOutData } from './envelopePageMessageOutData';

export interface EnvelopePageMessageOut {
  code?: number;
  message?: string;
  data?: EnvelopePageMessageOutData;
}
