/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { CurrentUserContext } from './currentUserContext';

export type EnvelopeCurrentUserContextData = CurrentUserContext | null;
