/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { EnvelopePageProjectOutData } from './envelopePageProjectOutData';

export interface EnvelopePageProjectOut {
  code?: number;
  message?: string;
  data?: EnvelopePageProjectOutData;
}
