/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeOut } from './intakeOut';

export interface HomeCardOutIntakeOut {
  total: number;
  items: IntakeOut[];
}
