/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { AgentActionOut } from './agentActionOut';

export interface HomeCardOutAgentActionOut {
  total: number;
  items: AgentActionOut[];
}
