/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { HomeCardOutWorkItemOut } from './homeCardOutWorkItemOut';
import type { HomeCardOutOverdueWorkItem } from './homeCardOutOverdueWorkItem';
import type { HomeCardOutAgentActionOut } from './homeCardOutAgentActionOut';
import type { HomeCardOutIntakeOut } from './homeCardOutIntakeOut';

export interface HomeSnapshotOut {
  myTodos: HomeCardOutWorkItemOut;
  overdue: HomeCardOutOverdueWorkItem;
  pendingAgentActions: HomeCardOutAgentActionOut;
  recentAiCreated: HomeCardOutWorkItemOut;
  pendingIntake: HomeCardOutIntakeOut;
}
