/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type IdentityProvider = typeof IdentityProvider[keyof typeof IdentityProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IdentityProvider = {
  local: 'local',
  multirag: 'multirag',
  oidc: 'oidc',
} as const;
