/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type InsightKind = typeof InsightKind[keyof typeof InsightKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsightKind = {
  risk: 'risk',
  overdue: 'overdue',
  high_priority: 'high_priority',
  workload: 'workload',
} as const;
