/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type InsightSeverity = typeof InsightSeverity[keyof typeof InsightSeverity];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InsightSeverity = {
  info: 'info',
  warning: 'warning',
  critical: 'critical',
} as const;
