/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { InsightKind } from './insightKind';
import type { InsightSeverity } from './insightSeverity';
import type { InsightOutMetrics } from './insightOutMetrics';
import type { InsightOutDetail } from './insightOutDetail';

export interface InsightOut {
  kind: InsightKind;
  severity: InsightSeverity;
  metrics: InsightOutMetrics;
  detail?: InsightOutDetail;
}
