/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type IntakeSource = typeof IntakeSource[keyof typeof IntakeSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntakeSource = {
  manual: 'manual',
  ai_chat: 'ai_chat',
  api: 'api',
  mcp: 'mcp',
} as const;
