/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeCreateInDescription } from './intakeCreateInDescription';

export interface IntakeCreateIn {
  /**
   * @minLength 1
   * @maxLength 300
   */
  title: string;
  description?: IntakeCreateInDescription;
}
