/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeUpdateInTitle } from './intakeUpdateInTitle';
import type { IntakeUpdateInDescription } from './intakeUpdateInDescription';
import type { IntakeUpdateInStatus } from './intakeUpdateInStatus';

export interface IntakeUpdateIn {
  title?: IntakeUpdateInTitle;
  description?: IntakeUpdateInDescription;
  status?: IntakeUpdateInStatus;
}
