/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type IntakeStatus = typeof IntakeStatus[keyof typeof IntakeStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IntakeStatus = {
  new: 'new',
  triaging: 'triaging',
  accepted: 'accepted',
  rejected: 'rejected',
  duplicate: 'duplicate',
  snoozed: 'snoozed',
  converted: 'converted',
} as const;
