/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeOutDescription } from './intakeOutDescription';
import type { IntakeSource } from './intakeSource';
import type { IntakeOutSourceRefId } from './intakeOutSourceRefId';
import type { IntakeStatus } from './intakeStatus';
import type { IntakeOutSubmitterId } from './intakeOutSubmitterId';
import type { IntakeOutAiSummary } from './intakeOutAiSummary';
import type { IntakeOutAiCategory } from './intakeOutAiCategory';
import type { IntakeOutSuggestedType } from './intakeOutSuggestedType';
import type { IntakeOutSuggestedPriority } from './intakeOutSuggestedPriority';
import type { IntakeOutSuggestedAssigneeId } from './intakeOutSuggestedAssigneeId';
import type { IntakeOutSuggestedAssignee } from './intakeOutSuggestedAssignee';
import type { IntakeOutTriageMeta } from './intakeOutTriageMeta';
import type { IntakeOutDuplicateWorkItemId } from './intakeOutDuplicateWorkItemId';
import type { IntakeOutConvertedWorkItemId } from './intakeOutConvertedWorkItemId';
import type { IntakeOutSnoozeUntil } from './intakeOutSnoozeUntil';
import type { IntakeOutRejectionReason } from './intakeOutRejectionReason';
import type { IntakeOutCreatedBy } from './intakeOutCreatedBy';
import type { IntakeOutUpdatedBy } from './intakeOutUpdatedBy';

export interface IntakeOut {
  id: string;
  projectId: string;
  title: string;
  description: IntakeOutDescription;
  source: IntakeSource;
  sourceRefId: IntakeOutSourceRefId;
  status: IntakeStatus;
  submitterId: IntakeOutSubmitterId;
  aiSummary: IntakeOutAiSummary;
  aiCategory: IntakeOutAiCategory;
  suggestedType: IntakeOutSuggestedType;
  suggestedPriority: IntakeOutSuggestedPriority;
  suggestedAssigneeId: IntakeOutSuggestedAssigneeId;
  suggestedAssignee: IntakeOutSuggestedAssignee;
  triageMeta: IntakeOutTriageMeta;
  duplicateWorkItemId: IntakeOutDuplicateWorkItemId;
  convertedWorkItemId: IntakeOutConvertedWorkItemId;
  snoozeUntil: IntakeOutSnoozeUntil;
  rejectionReason: IntakeOutRejectionReason;
  createdBy: IntakeOutCreatedBy;
  updatedBy: IntakeOutUpdatedBy;
  createdAt: string;
  updatedAt: string;
}
