/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeAcceptInType } from './intakeAcceptInType';
import type { IntakeAcceptInTitle } from './intakeAcceptInTitle';
import type { IntakeAcceptInPriority } from './intakeAcceptInPriority';
import type { IntakeAcceptInAssigneeId } from './intakeAcceptInAssigneeId';

/**
 * Overrides applied to the converted work item; unset fields fall back to the AI
suggestions, then to defaults (type=task, priority=medium).
 */
export interface IntakeAcceptIn {
  type?: IntakeAcceptInType;
  title?: IntakeAcceptInTitle;
  priority?: IntakeAcceptInPriority;
  assigneeId?: IntakeAcceptInAssigneeId;
}
