/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { InviteStatus } from './inviteStatus';
import type { InviteOutTenantRole } from './inviteOutTenantRole';
import type { InviteOutProjectId } from './inviteOutProjectId';
import type { InviteOutProjectRole } from './inviteOutProjectRole';

export interface InviteOut {
  id: string;
  email: string;
  status: InviteStatus;
  tenantRole: InviteOutTenantRole;
  projectId: InviteOutProjectId;
  projectRole: InviteOutProjectRole;
  expiresAt: string;
  createdAt: string;
}
