/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { InviteCreateInTenantRole } from './inviteCreateInTenantRole';
import type { InviteCreateInProjectId } from './inviteCreateInProjectId';
import type { InviteCreateInProjectRole } from './inviteCreateInProjectRole';

export interface InviteCreateIn {
  email: string;
  tenantRole?: InviteCreateInTenantRole;
  projectId?: InviteCreateInProjectId;
  projectRole?: InviteCreateInProjectRole;
}
