/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { InviteStatus } from './inviteStatus';
import type { InvitePreviewOutTenantRole } from './invitePreviewOutTenantRole';
import type { InvitePreviewOutProjectId } from './invitePreviewOutProjectId';
import type { InvitePreviewOutProjectName } from './invitePreviewOutProjectName';
import type { InvitePreviewOutProjectRole } from './invitePreviewOutProjectRole';

export interface InvitePreviewOut {
  email: string;
  status: InviteStatus;
  tenantRole: InvitePreviewOutTenantRole;
  projectId: InvitePreviewOutProjectId;
  projectName: InvitePreviewOutProjectName;
  projectRole: InvitePreviewOutProjectRole;
}
