/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type InviteStatus = typeof InviteStatus[keyof typeof InviteStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InviteStatus = {
  pending: 'pending',
  accepted: 'accepted',
  expired: 'expired',
  revoked: 'revoked',
} as const;
