/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { AuditActorType } from './auditActorType';
import type { AuditAction } from './auditAction';

export type ListAuditLogsParams = {
actor_type?: AuditActorType | null;
actor_id?: string | null;
resource_type?: string | null;
resource_id?: string | null;
project_id?: string | null;
action?: AuditAction | null;
created_from?: string | null;
created_to?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
