/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkItemStatus } from './workItemStatus';
import type { WorkItemType } from './workItemType';
import type { WorkItemPriority } from './workItemPriority';
import type { WorkItemSort } from './workItemSort';

export type ListWorkItemsParams = {
status?: WorkItemStatus | null;
type?: WorkItemType | null;
priority?: WorkItemPriority | null;
assignee_id?: string | null;
sort?: WorkItemSort;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
