/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { IntakeStatus } from './intakeStatus';
import type { IntakeSource } from './intakeSource';

export type ListIntakeParams = {
status?: IntakeStatus | null;
source?: IntakeSource | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
