/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { SkillInvocationStatus } from './skillInvocationStatus';
import type { RiskLevel } from './riskLevel';

export type ListSkillInvocationsParams = {
status?: SkillInvocationStatus | null;
risk_level?: RiskLevel | null;
tool_name?: string | null;
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
};
