/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { MessageRole } from './messageRole';
import type { MessageOutRunId } from './messageOutRunId';
import type { MessageOutAgentActionId } from './messageOutAgentActionId';
import type { MessageOutWorkItemId } from './messageOutWorkItemId';
import type { MessageOutKnowledgeRefs } from './messageOutKnowledgeRefs';
import type { MessageOutCreatedBy } from './messageOutCreatedBy';

export interface MessageOut {
  id: string;
  conversationId: string;
  role: MessageRole;
  content: string;
  runId: MessageOutRunId;
  agentActionId: MessageOutAgentActionId;
  workItemId: MessageOutWorkItemId;
  knowledgeRefs: MessageOutKnowledgeRefs;
  createdBy: MessageOutCreatedBy;
  createdAt: string;
}
