/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type MessageRole = typeof MessageRole[keyof typeof MessageRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageRole = {
  user: 'user',
  ai: 'ai',
  system: 'system',
} as const;
