/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkItemStatus } from './workItemStatus';
import type { WorkItemType } from './workItemType';
import type { WorkItemPriority } from './workItemPriority';
import type { OverdueWorkItemAssigneeId } from './overdueWorkItemAssigneeId';
import type { OverdueWorkItemAssignee } from './overdueWorkItemAssignee';
import type { WorkItemSource } from './workItemSource';

export interface OverdueWorkItem {
  id: string;
  key: string;
  title: string;
  status: WorkItemStatus;
  type: WorkItemType;
  priority: WorkItemPriority;
  assignee_id: OverdueWorkItemAssigneeId;
  assignee: OverdueWorkItemAssignee;
  due_at: string;
  days_overdue: number;
  source: WorkItemSource;
  created_at: string;
}
