/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { SkillInvocationOut } from './skillInvocationOut';

export interface PageSkillInvocationOut {
  items: SkillInvocationOut[];
  total: number;
  page: number;
  pageSize: number;
}
