/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type Permission = typeof Permission[keyof typeof Permission];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Permission = {
  tenantmanage: 'tenant.manage',
  userread: 'user.read',
  userinvite: 'user.invite',
  usermanage: 'user.manage',
  roleassign: 'role.assign',
  ai_agentread: 'ai_agent.read',
  ai_agentmanage: 'ai_agent.manage',
  auditread: 'audit.read',
  projectcreate: 'project.create',
  projectread: 'project.read',
  projectupdate: 'project.update',
  projectarchive: 'project.archive',
  projectmembermanage: 'project.member.manage',
  work_itemread: 'work_item.read',
  work_itemcreate: 'work_item.create',
  work_itemupdate: 'work_item.update',
  work_itemdelete: 'work_item.delete',
  work_itemtransition: 'work_item.transition',
  work_itemcomment: 'work_item.comment',
  work_itemassign: 'work_item.assign',
  skillread: 'skill.read',
  skillinvoke: 'skill.invoke',
  workchatuse: 'workchat.use',
  agent_actionconfirm: 'agent_action.confirm',
  intakeread: 'intake.read',
  intakecreate: 'intake.create',
  intaketriage: 'intake.triage',
  dashboardread: 'dashboard.read',
} as const;
