/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

/**
 * Settings Lite: the only self-editable profile field in v0.1 (password/avatar deferred).
 */
export interface ProfileUpdateIn {
  /**
   * @minLength 1
   * @maxLength 100
   */
  displayName: string;
}
