/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';
import type { Permission } from './permission';

export interface ProjectAccessOut {
  id: string;
  name: string;
  role: Role;
  permissions: Permission[];
}
