/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectMemberOutAvatarUrl } from './projectMemberOutAvatarUrl';
import type { ProjectMemberRole } from './projectMemberRole';

export interface ProjectMemberOut {
  userId: string;
  displayName: string;
  email: string;
  avatarUrl: ProjectMemberOutAvatarUrl;
  role: ProjectMemberRole;
  createdAt: string;
}
