/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectOutDescription } from './projectOutDescription';
import type { ProjectStatus } from './projectStatus';
import type { ProjectOutOwnerId } from './projectOutOwnerId';
import type { ProjectOutOwner } from './projectOutOwner';

export interface ProjectOut {
  id: string;
  name: string;
  key: string;
  description: ProjectOutDescription;
  status: ProjectStatus;
  ownerId: ProjectOutOwnerId;
  owner: ProjectOutOwner;
  memberCount: number;
  createdAt: string;
  updatedAt: string;
}
