/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type ProjectMemberRole = typeof ProjectMemberRole[keyof typeof ProjectMemberRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectMemberRole = {
  project_admin: 'project_admin',
  member: 'member',
  viewer: 'viewer',
} as const;
