/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectUpdateInName } from './projectUpdateInName';
import type { ProjectUpdateInDescription } from './projectUpdateInDescription';

export interface ProjectUpdateIn {
  name?: ProjectUpdateInName;
  description?: ProjectUpdateInDescription;
}
