/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectSummaryOutStatusCounts } from './projectSummaryOutStatusCounts';
import type { ProjectActivityOut } from './projectActivityOut';

export interface ProjectSummaryOut {
  totalCount: number;
  statusCounts: ProjectSummaryOutStatusCounts;
  highPriorityCount: number;
  overdueCount: number;
  aiCreatedCount: number;
  recentActivities: ProjectActivityOut[];
}
