/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ActivityAction } from './activityAction';
import type { ProjectActivityOutActorId } from './projectActivityOutActorId';

export interface ProjectActivityOut {
  id: string;
  workItemId: string;
  workItemKey: string;
  workItemTitle: string;
  action: ActivityAction;
  actorType: string;
  actorId: ProjectActivityOutActorId;
  createdAt: string;
}
