/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectCreateInDescription } from './projectCreateInDescription';

export interface ProjectCreateIn {
  /**
   * @minLength 1
   * @maxLength 200
   */
  name: string;
  key: string;
  description?: ProjectCreateInDescription;
}
