/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { RelationType } from './relationType';

export interface RelationCreateIn {
  type: RelationType;
  targetWorkItemId: string;
}
