/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type RelationDirection = typeof RelationDirection[keyof typeof RelationDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RelationDirection = {
  outgoing: 'outgoing',
  incoming: 'incoming',
} as const;
