/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { RelationType } from './relationType';
import type { RelationDirection } from './relationDirection';
import type { WorkItemBriefOut } from './workItemBriefOut';

export interface RelationOut {
  id: string;
  type: RelationType;
  direction: RelationDirection;
  related: WorkItemBriefOut;
  createdAt: string;
}
