/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type RelationType = typeof RelationType[keyof typeof RelationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RelationType = {
  parent_child: 'parent_child',
  blocks: 'blocks',
  blocked_by: 'blocked_by',
  duplicates: 'duplicates',
  relates_to: 'relates_to',
  created_from_message: 'created_from_message',
  created_from_intake: 'created_from_intake',
} as const;
