/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

/**
 * AI action risk (D4). Shared semantics with MCP tags / AgentAction (M5).
 */
export type RiskLevel = typeof RiskLevel[keyof typeof RiskLevel];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RiskLevel = {
  read: 'read',
  low_write: 'low_write',
  high_write: 'high_write',
} as const;
