/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type Role = typeof Role[keyof typeof Role];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Role = {
  owner: 'owner',
  admin: 'admin',
  project_admin: 'project_admin',
  member: 'member',
  viewer: 'viewer',
  ai_agent: 'ai_agent',
} as const;
