/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { SkillInvocationOutRepresentedUser } from './skillInvocationOutRepresentedUser';
import type { SkillInvocationOutProjectId } from './skillInvocationOutProjectId';
import type { SkillInvocationOutConversationId } from './skillInvocationOutConversationId';
import type { SkillInvocationOutRunId } from './skillInvocationOutRunId';
import type { SkillInvocationOutOutputSummary } from './skillInvocationOutOutputSummary';
import type { SkillInvocationStatus } from './skillInvocationStatus';
import type { RiskLevel } from './riskLevel';
import type { SkillInvocationOutAgentActionId } from './skillInvocationOutAgentActionId';
import type { SkillInvocationOutAuditLogId } from './skillInvocationOutAuditLogId';
import type { SkillInvocationOutErrorMessage } from './skillInvocationOutErrorMessage';
import type { SkillInvocationOutFinishedAt } from './skillInvocationOutFinishedAt';

export interface SkillInvocationOut {
  id: string;
  skillCode: string;
  toolName: string;
  callerType: string;
  callerId: string;
  representedUserId: string;
  representedUser?: SkillInvocationOutRepresentedUser;
  agentId: string;
  projectId: SkillInvocationOutProjectId;
  conversationId: SkillInvocationOutConversationId;
  runId: SkillInvocationOutRunId;
  inputSummary: string;
  outputSummary: SkillInvocationOutOutputSummary;
  status: SkillInvocationStatus;
  riskLevel: RiskLevel;
  requiresConfirmation: boolean;
  agentActionId: SkillInvocationOutAgentActionId;
  auditLogId: SkillInvocationOutAuditLogId;
  errorMessage: SkillInvocationOutErrorMessage;
  startedAt: string;
  finishedAt: SkillInvocationOutFinishedAt;
  createdAt: string;
}
