/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { SkillToolOut } from './skillToolOut';

export interface SkillOut {
  skillCode: string;
  tools: SkillToolOut[];
}
