/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { SkillToolOutRiskLevel } from './skillToolOutRiskLevel';
import type { SkillToolOutRequiredPermission } from './skillToolOutRequiredPermission';

export interface SkillToolOut {
  toolName: string;
  riskLevel: SkillToolOutRiskLevel;
  executableInV01: boolean;
  requiredPermission: SkillToolOutRequiredPermission;
}
