/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type SkillInvocationStatus = typeof SkillInvocationStatus[keyof typeof SkillInvocationStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SkillInvocationStatus = {
  running: 'running',
  success: 'success',
  failed: 'failed',
  blocked: 'blocked',
  rejected: 'rejected',
} as const;
