/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { UserOutAvatarUrl } from './userOutAvatarUrl';
import type { IdentityProvider } from './identityProvider';
import type { UserOutExternalUserId } from './userOutExternalUserId';

export interface UserOut {
  id: string;
  email: string;
  displayName: string;
  avatarUrl: UserOutAvatarUrl;
  identityProvider: IdentityProvider;
  externalUserId: UserOutExternalUserId;
}
