/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { UserListOutAvatarUrl } from './userListOutAvatarUrl';
import type { IdentityProvider } from './identityProvider';
import type { UserListOutExternalUserId } from './userListOutExternalUserId';
import type { UserStatus } from './userStatus';
import type { UserListOutLastLoginAt } from './userListOutLastLoginAt';

export interface UserListOut {
  id: string;
  email: string;
  displayName: string;
  avatarUrl: UserListOutAvatarUrl;
  identityProvider: IdentityProvider;
  externalUserId: UserListOutExternalUserId;
  status: UserStatus;
  lastLoginAt: UserListOutLastLoginAt;
  createdAt: string;
}
