/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type WorkItemStatus = typeof WorkItemStatus[keyof typeof WorkItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemStatus = {
  backlog: 'backlog',
  todo: 'todo',
  in_progress: 'in_progress',
  review: 'review',
  done: 'done',
  cancelled: 'cancelled',
} as const;
