/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkItemType } from './workItemType';
import type { WorkItemCreateInDescription } from './workItemCreateInDescription';
import type { WorkItemPriority } from './workItemPriority';
import type { WorkItemCreateInAssigneeId } from './workItemCreateInAssigneeId';
import type { WorkItemCreateInDueAt } from './workItemCreateInDueAt';
import type { WorkItemCreateInAcceptanceCriteria } from './workItemCreateInAcceptanceCriteria';
import type { WorkItemCreateInCustomFields } from './workItemCreateInCustomFields';

export interface WorkItemCreateIn {
  type: WorkItemType;
  /**
   * @minLength 1
   * @maxLength 300
   */
  title: string;
  description?: WorkItemCreateInDescription;
  priority?: WorkItemPriority;
  assigneeId?: WorkItemCreateInAssigneeId;
  dueAt?: WorkItemCreateInDueAt;
  tags?: string[];
  acceptanceCriteria?: WorkItemCreateInAcceptanceCriteria;
  customFields?: WorkItemCreateInCustomFields;
}
