/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkItemType } from './workItemType';
import type { WorkItemOutDescription } from './workItemOutDescription';
import type { WorkItemStatus } from './workItemStatus';
import type { WorkItemPriority } from './workItemPriority';
import type { WorkItemOutAssigneeId } from './workItemOutAssigneeId';
import type { WorkItemOutAssignee } from './workItemOutAssignee';
import type { WorkItemOutReporterId } from './workItemOutReporterId';
import type { WorkItemOutDueAt } from './workItemOutDueAt';
import type { WorkItemSource } from './workItemSource';
import type { WorkItemOutSourceRefId } from './workItemOutSourceRefId';
import type { WorkItemOutAiSummary } from './workItemOutAiSummary';
import type { WorkItemOutAcceptanceCriteria } from './workItemOutAcceptanceCriteria';
import type { WorkItemOutCustomFields } from './workItemOutCustomFields';
import type { WorkItemOutCreatedBy } from './workItemOutCreatedBy';
import type { WorkItemOutUpdatedBy } from './workItemOutUpdatedBy';

export interface WorkItemOut {
  id: string;
  key: string;
  projectId: string;
  seq: number;
  type: WorkItemType;
  title: string;
  description: WorkItemOutDescription;
  status: WorkItemStatus;
  priority: WorkItemPriority;
  assigneeId: WorkItemOutAssigneeId;
  assignee: WorkItemOutAssignee;
  reporterId: WorkItemOutReporterId;
  dueAt: WorkItemOutDueAt;
  tags: string[];
  source: WorkItemSource;
  sourceRefId: WorkItemOutSourceRefId;
  aiSummary: WorkItemOutAiSummary;
  acceptanceCriteria: WorkItemOutAcceptanceCriteria;
  customFields: WorkItemOutCustomFields;
  createdBy: WorkItemOutCreatedBy;
  updatedBy: WorkItemOutUpdatedBy;
  createdAt: string;
  updatedAt: string;
}
