/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type WorkItemType = typeof WorkItemType[keyof typeof WorkItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemType = {
  task: 'task',
  requirement: 'requirement',
  bug: 'bug',
  risk: 'risk',
  decision: 'decision',
  approval: 'approval',
  incident: 'incident',
  feedback: 'feedback',
} as const;
