/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type WorkItemPriority = typeof WorkItemPriority[keyof typeof WorkItemPriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  urgent: 'urgent',
} as const;
