/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkItemUpdateInTitle } from './workItemUpdateInTitle';
import type { WorkItemUpdateInDescription } from './workItemUpdateInDescription';
import type { WorkItemUpdateInPriority } from './workItemUpdateInPriority';
import type { WorkItemUpdateInAssigneeId } from './workItemUpdateInAssigneeId';
import type { WorkItemUpdateInDueAt } from './workItemUpdateInDueAt';
import type { WorkItemUpdateInTags } from './workItemUpdateInTags';
import type { WorkItemUpdateInAiSummary } from './workItemUpdateInAiSummary';
import type { WorkItemUpdateInAcceptanceCriteria } from './workItemUpdateInAcceptanceCriteria';
import type { WorkItemUpdateInCustomFields } from './workItemUpdateInCustomFields';

export interface WorkItemUpdateIn {
  title?: WorkItemUpdateInTitle;
  description?: WorkItemUpdateInDescription;
  priority?: WorkItemUpdateInPriority;
  assigneeId?: WorkItemUpdateInAssigneeId;
  dueAt?: WorkItemUpdateInDueAt;
  tags?: WorkItemUpdateInTags;
  aiSummary?: WorkItemUpdateInAiSummary;
  acceptanceCriteria?: WorkItemUpdateInAcceptanceCriteria;
  customFields?: WorkItemUpdateInCustomFields;
}
