/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkloadItemOutAssigneeId } from './workloadItemOutAssigneeId';
import type { WorkloadItemOutAssignee } from './workloadItemOutAssignee';
import type { WorkloadItemOutStatusCounts } from './workloadItemOutStatusCounts';

export interface WorkloadItemOut {
  assigneeId: WorkloadItemOutAssigneeId;
  assignee: WorkloadItemOutAssignee;
  totalCount: number;
  statusCounts: WorkloadItemOutStatusCounts;
  overdueCount: number;
  highPriorityCount: number;
}
