/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type WorkItemSort = typeof WorkItemSort[keyof typeof WorkItemSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemSort = {
  created_desc: 'created_desc',
  created_asc: 'created_asc',
  updated_desc: 'updated_desc',
  updated_asc: 'updated_asc',
} as const;
