/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */
import type { WorkItemType } from './workItemType';
import type { WorkItemStatus } from './workItemStatus';

export interface WorkItemBriefOut {
  id: string;
  key: string;
  title: string;
  type: WorkItemType;
  status: WorkItemStatus;
}
