/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * WorkNexus
 * OpenAPI spec version: 0.1.0
 */

export type WorkItemSource = typeof WorkItemSource[keyof typeof WorkItemSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkItemSource = {
  manual: 'manual',
  ai_chat: 'ai_chat',
  intake: 'intake',
  mcp: 'mcp',
  api: 'api',
} as const;
