export const paths = {
  home: () => '/',
  login: () => '/login',
  setup: () => '/setup',
  invite: (token: string) => `/invites/${token}`,
  projects: () => '/projects',
  projectDetail: (id: string) => `/projects/${id}`,
  workItems: (projectId: string) => `/projects/${projectId}/work-items`,
  board: (projectId: string) => `/projects/${projectId}/board`,
  intake: (projectId: string) => `/projects/${projectId}/intake`,
  dashboard: (projectId: string) => `/projects/${projectId}/dashboard`,
  ai: (projectId: string) => `/projects/${projectId}/ai`,
  skills: () => '/skills',
  audit: () => '/audit',
  settingsMembers: () => '/settings/members',
} as const
